"""empty message

Revision ID: 60c0eefaefbf
Revises: fec909733f46
Create Date: 2021-05-29 19:16:14.047234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60c0eefaefbf'
down_revision = 'fec909733f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_classes_name', table_name='classes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_classes_name', 'classes', ['name'], unique=1)
    # ### end Alembic commands ###
