"""empty message

Revision ID: 82eafa398fed
Revises: 35f884b9ec77
Create Date: 2021-05-29 13:30:14.039006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82eafa398fed'
down_revision = '35f884b9ec77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('catagory', sa.String(length=64), nullable=True),
    sa.Column('whatClasses', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_catagory'), 'books', ['catagory'], unique=False)
    op.create_index(op.f('ix_books_name'), 'books', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_name'), table_name='books')
    op.drop_index(op.f('ix_books_catagory'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
